name: Test with Docker Compose

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      DJANGO_DEBUG: ${{ vars.DJANGO_DEBUG }}
      DB_ENGINE: ${{ vars.DB_ENGINE }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_NAME: ${{ vars.DB_NAME }}
      DB_PORT: ${{ vars.DB_PORT }}

      DJANGO_LOGLEVEL: ${{ vars.DJANGO_LOGLEVEL }}
      DJANGO_ALLOWED_HOSTS: ${{ vars.DJANGO_ALLOWED_HOSTS }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: List versions
        run: |
          docker version
          docker compose version

      - name: Build services
        run: docker compose build

      - name: Bring up services
        run: docker compose up -d

      - name: Migrate db
        run: docker compose exec web python manage.py migrate

      - name: Django check
        run: docker compose exec web python manage.py check

      - name: Django tests
        run: docker compose exec web python manage.py test

      - name: Tear down services
        run: docker compose down

      - name: Log in to Docker Hub
        if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Push images to Docker Hub
        if: ${{ github.ref_name == 'main' || github.ref_name == 'staging' }}
        run:  |
          docker tag \
            VESCtige-web:latest \
            bhinesley/VESCtige:${{ github.ref_name }}
          docker push bhinesley/VESCtige:${{ github.ref_name }}
